### ISSUE TITLE
How to read aloud two language subtitle at once

### ISSUE THREAD

**Issue by trionline1234** [limura/CaptionSpeaker#10]
I think it will be better for language learner when listen two language subtitles at once, first for mother language, second for original sound of video. It may be pause a little bit when read mother language first, after play video for that sentence.

**Comment by limura** [comment]
2つの言語を同時に読み上げるというのはどういう状態でしょうか。よくわかりませんでしたのでもう少し具体的な例を用いるなどして説明していただけますか？

1つは母国語、というと、こちらはCaptionSpeakerの機能で字幕をSpeechSynthesisを使って読み上げさせている物になりそうです。
2番めがビデオの原音というと、これはそのままビデオ側で発音しているのでわざわざ読み上げさせる必要はないと思います。

なお、CaptionSpeakerの使っているSpeechSynthesisは、2つ同時に発話することはできなさそうです。正確には、一つの発話中に別の発話を行おうとすると以前の発話を止めてから発話するか、止めない場合は以前の発話が終わった後に発話されるqueueのようなものに追加されるような挙動になるはずです。

**Comment by trionline1234** [comment]
i means that, firstly pause video and text-to-speech for the mother language(translated) sentence, secondly, play video at that sentence(not text-to-speech).
Extension can have more option such as number of loop that sentence as well as speed for each loop.

**Comment by limura** [comment]
すみません。よくわかりませんでした。

・何を目的としているのか
・何ができていないのか
・何ができるとその問題が解決するのか

のどれもわかりませんでした。

片方の言語で発話した後に別の言語で発話するという話でしょうか。
CaptionSpeakerのアイコンをクリックして字幕の読み上げのON/OFFを切り替える事ができるので、それで回避できる問題ではありませんか？

**Comment by trionline1234** [comment]
It is just automatically for all sentences(pause ->read aloud the translated sentence(TTS)-> play video at that sentence and loop 5 times video at that sentence=> go on with the next sentence and so on).

**Comment by limura** [comment]
それを自動で行うと嬉しいシチュエーションが理解できません。何も、理解できていません。
もし、私を働かせるつもりがあるのなら、私が理解できるように言葉や他の色々な物を尽くして説明してください。

・何を目的としていますか？
・それができるようになると嬉しいと感じる人はどの程度の数存在しますか？
・現状のままではできない理由は何ですか？

少なくとも、今の時点では私は何も理解できていません。
そのため、何をすれば良いのかもわかりませんし、それをして嬉しくなる人が居るのか居ないのかの想像もできていません。
嬉しくなる人が居ない場合はそれを実装する必要は無いと思いますし、そのような人が居るにしても、CaptionSpeakerの対象としている人にそのような人があまり存在しないのであればCaptionSpeaker以外のプロダクトがそれを実装すれば良いのではないかと思います。

私は貴方が望まれている事を理解したいのですが、何を説明されているのかすらわかっていません。これでは、何か手を差し伸べようにも何もできません。
正直な所、私が質問した事の一部しか答えてくれないのであれば、これ以上会話をする意味が見いだせません。

**Comment by trionline1234** [comment]
Bilingual listening will help languge learner, i hope you can understand.
https://www.youtube.com/watch?v=QllKhDdgY-4

**Comment by limura** [comment]
すみません。その動画には字幕が設定されていないようです。その動画で何が語られているのかを私は全く認識できませんでした。
従って、私はその動画から何の情報も得られていません。

申し訳ないのですが、以前の投稿でも申し上げました通り、私は貴方が何を求めているのかすら理解できていません。
これでは何かしようにも何もできません。

できれば説明して欲しいのですが、それも得られないようです。

私の言っている事はわかりますか？

**Comment by trionline1234** [comment]
sorry for my poor expression, that video is simply bilingual audio, you don't need to understand its content.
This extension should loop each subtitle sentence many times with different speeds from slow to fast (listener can listen carefully and shadowing), and before that looping, this extension will read aloud(TTS) that translated subtitle sentence to listener can understand the looped sentence.
I hope you can understand my thought.

**Comment by limura** [comment]
何度もすみません。やはりよくわかりませんでした。

それはあなたが実行したい事ですか？
あなたが求めている「目的」は何ですか？
実際の動作の前に、「何をするためなのか」といった「目的」を明らかにしてください。
その次に、「その目的に対して何が足りていない」という形で問題点を明らかにしてください。
その次に、「このように動作することで目的を達することができる」という形で、動作をできるだけ正確に記述してください。
というような順番で表現していただくのが恐らくわかりやすいです。

あなたの書いている事は最後の動作部分しかかかれていないように見えています。
これでは何を目的としているのかがわからず、そもそもその動作が何故必要なのかもわかりません。
その動作が必要なのかがわからなければ、その動作を実装する必要があるのかすら判断できません。

すみませんが本当に説明が足りません。私を動かしたいのなら言葉を尽くしてください。よろしくお願いします。

**Comment by limura** [comment]
しばらく待ちましたが私が理解できるような説明がなされなかったためクローズします。
