### ISSUE TITLE
Problem where speech stops after three seconds.

### ISSUE THREAD

**Issue by murillodutt** [limura/CaptionSpeaker#3]
Dear Takuji,

I noticed that on my three macOS 12 (Monterey) computers, the audio transcription stops after a few seconds.

I noticed that on my three macOS 12 (Monterey) computers, the audio transcription stops after a few seconds. I ran the script code and still haven't identified what could be causing this. I ran the same test with Chrome (Version 101.0.4951.64), Chrome (Version 103.0.5060.0) and Edge (Version 101.0.1210.39).

look the example

https://user-images.githubusercontent.com/9220796/168280187-95031f84-777e-4bcb-aa4c-e9031732288b.mp4

**Comment by limura** [comment]
動画は確認できたのですが、こちらの環境では再現できていません。
(また、動画の解像度が低すぎて設定項目の詳細などが確認できません)
以下のような詳細な動作環境の情報は提供できますか？

・利用中のOS, OS Version
・テストに使用したYoutube動画のURL
・CaptionSpeakerの設定項目の全て

**Comment by murillodutt** [comment]
・two macs with  macOS Monterey Version 12.3.1 and one  12.2
・URL Movie test: https://www.youtube.com/watch?v=l7R_MDkTk8k

this glitch seems to happen only when the subtitle automatically generated. Here is the video again. 

I want to maintain a git repository of your work in Brazilian Portuguese.

https://github.com/murillopaiva/CaptionSpeakerBR

**Comment by limura** [comment]
提供頂いたURLのYoutube動画で確認してみましたが、私の環境(日本語での読み上げ)では再現しませんでした。

再度お尋ねしますが、CaptionSpeaker の設定項目の全ては提供できますか？

ところで、close されているようなのはこれ以上はこちらからは何もしないでも良いという事でしょうか？

また、ブラジル語へのポートはご自由になさってください。
なお、_locales/pt_BR/messages.json を pull request して頂いても良いですが、新しいメッセージなどは自動翻訳で挿入する事になります。(おそらくは、その都度 pull request していただくような形になりそうに思います)

**Comment by murillodutt** [comment]
![2022-05-13_09-40-29](https://user-images.githubusercontent.com/9220796/168285099-3eabbe07-11cb-44f8-a47b-dcd0eead985d.png)

**Comment by limura** [comment]
確認できました。
こちらの環境では、speaker の locale 設定をうまく反映できずに、ja locale (日本語)の字幕を読み込んでいるために、ブラジル語では再生できていないように見えています。

ただ、その場合は目的の言語での字幕を再度読み込みに行くはずでしたが、「同じYoutube動画（VideoIDが同一)であり、強制的に読み込むフラグが立っていない」条件にひっかかって字幕の読み込みが阻止されていました。

この問題について、以下のように修正しました。
https://github.com/limura/CaptionSpeaker/commit/8823d4f05f6811ab6babcf5a2909c8d2cf916862

**Comment by murillodutt** [comment]
Congratulations on your agility and availability. 🥇
