### ISSUE TITLE
please support persion(farsi) language :: fa-IR

### ISSUE THREAD

**Issue by bugbounted** [limura/CaptionSpeaker#4]
Hi [IIMURA Takuji](https://github.com/limura) ,
please support persion(farsi) language :: fa-IR
waiting for your commits :)
finest regards

**Comment by limura** [comment]
Hi.

Unfortunately I do not understand the fa-IR language at all.

I suppose you could provide fa-IR language support by pull request. However, I will probably not be able to continue to maintain fa-IR language support.

How do you suggest I do this? Do you have any suggestions?

**Comment by bugbounted** [comment]
hello again [IIMURA Takuji](https://github.com/limura),
you can easily use eSpeakPlus :
https://mahmood-taghavi.github.io/eSpeakPlus
or using tihu:
https://github.com/elmirarokni/tihu
persian language is same as arabic language but with little bit changes :
arabic not have 4 characters exist in persian , is گ چ پ ژ
& persian also not have diacritic letters must use in arabic.
regards

**Comment by limura** [comment]
Well, I thought you were looking for fa-IR language support. But are you talking about the fact that the fa-IR language doesn't exist as the language that CaptionSpeaker speaks to?

If so, please contact your OS or Google Chrome support.

In addition, the method of adding a language for speaking to Windows seems to be introduced in the following places, for example.
https://support.microsoft.com/en-us/topic/download-voices-for-immersive-reader-read-mode-and-read-aloud-4c83a8d8-7486-42f7-8e46-2b0fdf753130
However, I'm not sure if the above article will support your desired language.

In a previous post, I talked about CaptionSpeaker localization.
About localization
https://github.com/limura/CaptionSpeaker/tree/master/CaptionSpeaker/_locales
Below you can "you" make a pull request to add the fa-IR language.
However, I don't think I can maintain the localization of the fa-IR language after that.

**Comment by limura** [comment]
Note that CaptionSpeaker uses window.speechSynthesis for speech.
https://developer.mozilla.org/en-US/docs/Web/API/Window/speechSynthesis

If you are using GoogleChrome and you call
SpeechSynthesis.getVoices()
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/getVoices
and your desired language (fa-IR language) does not appear as available, it means that your GoogleChrome does not support it.

In that case, you need to configure your OS (or Google Chrome) to speak the expected language in some way.
CaptionSpeaker does not provide support on how to do this. You are on your own.

**Comment by bugbounted** [comment]
can you make new branch for CaptionSpeaker project to use eSpeakPlus as tts engine ?

**Comment by limura** [comment]
No. I have no intention of expanding support for eSpeakPlus.
