### ISSUE TITLE
This is not issue it is feature request. Pause playing original video.

### ISSUE THREAD

**Issue by deweloprela** [limura/CaptionSpeaker#5]
Can you please add feature to pause video while translation speaks? I mean, video say sentence for example and pause, than translator speaks, then video starts again. Thanks!

**Comment by limura** [comment]
新機能のご提案ありがとうございます。

簡易的な実装を手元で行ってみましたが、字幕が表示されるタイミングと動画を止めるタイミングがうまく噛み合わない問題があり、少々使いづらそうな気がしています。

これは、発話が開始される時間を1秒間隔の分解能のデータとして保持した上で、0.25秒間隔のタイミングで検出しているためです。
そのため、画面上にはまだ字幕が表示されていない間に発話が開始されてしまう場合があります。
少し使ってみた範囲ではかなりの頻度で起こるため、これを改善したほうが良いと考えています。
ただ、このタイミング周りはあまり手を出したくありません。
何か良い解決策は思いつきますか？

なお、この問題の実験は貴方の手元でも簡単に試す事ができます。
具体的には contentScript.js の volumeOverride と volumeRecover を以下のように書き換えると試すことができます。

https://github.com/limura/CaptionSpeaker/blob/7d527d140b76b64035c660a58494acdcc1b03057/CaptionSpeaker/contentScript.js#L293-L302


```JavaScript
function volumeOverride(videoElement, originalVolume, targetVolumeMagnification){
  overrideVolumeCount += 1;
  videoElement.pause();
}
function volumeRecover(videoElement, originalVolume){
  overrideVolumeCount -= 1;
  if(overrideVolumeCount <= 0){
    videoElement.play();
  }
}
```

操作としては videoElement.volume への操作を pause() と play() にするだけです。
この書き換えを行った後、CaptionSpeaker の設定の「発話中に元動画の音量を下げる(比率で指定します)」の項目をONにすると発話中はビデオの再生が停止するようになります。

**Comment by limura** [comment]
何か良い解決策はありませんか？

無いようなら一旦closeします。

**Comment by limura** [comment]
なお、Youtube動画の字幕は単語単位で表示される場合があります。
例えば https://www.youtube.com/watch?v=zMzDeMdGnew の英語字幕はそのような表示をします。
(11秒辺りでは "it" しか表示されておらず、1単語づつ表示され、12秒辺りで "it was a simple perimeter scan" と1行のすべてが表示されます。これは私が用いている日本語の字幕でも同様の動作をします)

CaptionSpeaker側ではこれらの1単語づつの表示は1行単位に纏めて管理しており、SpeechSynthesis での発話はこの1行単位での発話になっています。
そのため、CaptionSpeaker側が発話を開始した時にはその1行分の字幕すべてが表示されていない事になります。

この時、CaptionSpeaker側での発話時に動画を停止すると、字幕の表示は1行分の最初を表示した所で止まったままで、発話だけがすべてされる事になります。
私はこれを良くないと考えています。
というのは、私の場合は字幕での表示とCaptionSpeakerによる読み上げの両方を使って内容を認識しているようで、字幕の表示がされていないでCaptionSpeakerのよる読み上げのみでは理解しにくい場合があるからです。

できることなら、最初の1単語を表示する時に1行分すべての字幕を表示できるようになっていると良いのかもしれませんが、それはYoutube側の動作を変更する事になるため、やるべきではないと考えています。(もしできたとしても、やるべきではないという意味です)

上記の問題は恐らく簡単には解決できません。

落とし所としては、「発話時に動画の再生を止める」というON/OFFの設定項目を増やして実装する事が良さそうな気はします。しかしながら、「発話時に動画の再生を止めた場合に字幕の表示が遅れてしまうので早めにすべて表示できないか？」という問い合わせが増える事が予想されます(私はそう言いたくなります)。
その問い合わせをわざわざ増やすための修正になってしまうと、私がその問い合わせへの対応をする時間が取られるだけのつまらない修正になってしまうという点が懸念点として残ります。

この手の機能追加にはつきものの悩みですが、どうしたものですかね。

**Comment by limura** [comment]
特に新たな提案も無いようなのでcloseします。
