### ISSUE TITLE
How to add pause so that while subtitles are being played - the original video is on pause?

### ISSUE THREAD

**Issue by lofti198** [limura/CaptionSpeaker#9]
Hallo! Cool extension! How to add pause so that while subtitles are being played - the original video is on pause?

**Comment by limura** [comment]
Hello.
Unfortunately, we do not offer such a mechanism at this time.

If I were to rewrite it, I would probably rewrite the AddSpeechQueue() area.
https://github.com/limura/CaptionSpeaker/blob/1f9553740a0709d34957ada589caf2679104a7aa/CaptionSpeaker/contentScript.js#L304

The original Japanese text is shown below.


こんにちは。
残念ながら、今の所そのような仕組みは提供しておりません。

書き換えるとすると、 AddSpeechQueue() 辺りの部分を書き換える感じでしょうか。
https://github.com/limura/CaptionSpeaker/blob/1f9553740a0709d34957ada589caf2679104a7aa/CaptionSpeaker/contentScript.js#L304

**Comment by limura** [comment]
特に返信も無いようなのでcloseします。
